# Use docker-compose for easy local deployment
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
